#!/bin/bash
PIES="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpii18 rpi19 rpi20"

for a in $PIES ; do
	ping -c 1 -w 10 a
	if [ $? -eq 0 ]; then
	echo $a "is alive"
	fi
done

